spring:
  kafka:
    listener:
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: POSTGRES
    url: jdbc:postgresql://localhost:5432/orderdb
    username: orderuser
    password: ordermanagement1234